import type { Metadata } from 'next'
import { Open_Sans as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const openSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/favicon.ico'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'bg-background min-h-screen font-sans antialiased',
          openSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
